# ============================================
# NAMESPACE
# ============================================
# #### Creates the payflow namespace used to isolate all Payflow workloads. ####
# #### Apply this before any namespaced resources. ####
# #### Namespace to isolate all Payflow resources ####
apiVersion: v1
kind: Namespace
metadata:
  name: payflow
  labels:
    name: payflow
    app: payflow-wallet
    environment: development
